### ISSUE TITLE
Nom du package

### ISSUE THREAD

**Issue by vybduchene** [WaterWavesModels/WaterWaves1D.jl#12]
Notre meeting m'a fait repenser au problème du nom du package.
Pro : j'utilise déjà ce lien dans mon Habilitation.
Con : il n'est pas très fidèle a la réalité. La preuve, je compte l'utiliser dans un papier s'appelant "[...] deep water [...]"

Un nom plus fidèle (et plus stable) serait par exemple 1dWaterWaves 
(sous réserve de ne pas se lancer dans le 2d, mais la stratégie pour le modèle de référence "exact" est vraiment 1d)

Question : est-il possible et facile de
1) renommer le package en 1dWaterWaves
2) faire une redirection de ShallowWaterModels vers 1dWaterWaves. Ou à défaut de laisser une coquille vide dont la documentation dirait : This package has moved to 1dWaterWaves.jl

**Comment by pnavaro** [comment]
On ne peut pas commencer le nom de package par 1 . je propose OneDWaterWaves.jl 
Il suffit de changer le nom de dépôt, et modifier quelques fichiers.

**Comment by vybduchene** [comment]
Quel dommage. WaterWaves1d marcherait ?

**Comment by pnavaro** [comment]
Oui c'est bon.

**Comment by vybduchene** [comment]
Je préfèrerai si possible WaterWaves1D.jl que WaterModels1D.jl...

**Comment by pnavaro** [comment]
Oups, je me suis trompé désolé...
