### ISSUE TITLE
Run failed: CI, Attempt #2 - master (3772d3e)

### ISSUE THREAD

**Issue by vybduchene** [WaterWavesModels/WaterWaves1D.jl#14]
Je ne comprends pas pourquoi les tests ne passent pas sur la dernière version du package. Plus étrange, ils passent sur MacOS et Windows, mais pas Ubuntu (et documentation). Ils passent aussi en local, sur ma machine...

**Comment by pnavaro** [comment]
J'essaye de compiler le package mais j'ai cette erreur
```
ERROR: LoadError: SystemError: opening file "/home/pnavaro/WaterWaves1D.jl/src/figures.jl": Aucun fichier ou dossier de ce type
```

**Comment by pnavaro** [comment]
Je comprends osx et windows ne font pas la différence entre "figures.jl" et "Figures.jl" alors linux oui.
