### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by vybduchene** [WaterWavesModels/WaterWaves1D.jl#15]
Concernant la documentation

Première question : Est-ce normale qu'elle soit hébergée à cette adresse
https://waterwavesmodels.github.io/WaterWaves1D.jl/dev/
et pas, typiquement,
https://github.com/WaterWavesModels/WaterWaves1D.jl/docs/
Ce qui me gêne en particulier est que https://waterwavesmodels.github.io/ est pratiquement vide, et le lien cassé.

Deuxième question : comment faire en pratique lorsque je veux travailler sur la doc ? Je voudrais éviter d'avoir à faire des push, et attendre que la doc se mettre à jour, pour pouvoir vérifier la mise en forme, les liens, etc.

Troisième question : https://waterwavesmodels.github.io/WaterWaves1D.jl/dev/contents/ ne se met pas bien à jour (ici j'ai deux sections "Initial data" dont une obsolète)

Je sais : trois questions dans une Issue n'est pas du tout de la bonne pratique ;)

**Comment by pnavaro** [comment]
Bonjour Vincent,

# Question 1

Par défaut la documentation courante est dans le répertoire `dev` ensuite si il y a des releases du package et que celui-ci est enregistré, il y a la doc de cette version que sera dans le répertoire `stable`. C'est l'usage en julia. Tu peux changer le répertoire `dev` pour `docs`, il y a juste une option `devurl` à ajouter dans le fichier `make.jl`  https://juliadocs.github.io/Documenter.jl/stable/lib/public/#Documenter.deploydocs
Pour corriger le lien cassé il faut aller dans https://github.com/WaterWavesModels/WaterWavesModels.github.io
et changer l'url dans le fichier  `index.md` . J'avais fait ce petit site au cas ou il y aurait plusieurs packages.

# Question 2

Tu peux travailler en local sur la doc, il faut faire

```
$ julia --project=docs/
pkg> instantiate
pkg> dev .
julia> using Revise
julia> include("docs/make.jl")
shell> open docs/build/index.html
```
Après chaque modification, tu répètes 
```
julia> include("docs/make.jl")
```
Et la doc sera mise à jour.

# Question 3

`contents` est généré de manière automatique. L'erreur est dans le fichier `docs/src/basics.md` qui fait référence à ces fonctions obsolètes.

Je suis à l'IRMAR demain et jeudi, n'hésite pas si il y a un souci.

Pierre
