### ISSUE TITLE
multithreading

### ISSUE THREAD

**Issue by vybduchene** [WaterWavesModels/WaterWaves1D.jl#17]
Un problème avec solve!(problems), appliqué avec plusieurs problèmes. 
Les résultats ne sont pas les bons (c'est pourquoi le test dans testtypes échoue).
Je pense que c'est dû au fait qu'il y a des pré-allocations, qui sont utilisées en même temps par les différents thread.
Mais je n'ai pas réussi à débugger.
Il y a bien-sûr la possibilité de retirer le @thread, mais on perd l'intérêt de la chose...

**Comment by vybduchene** [comment]
J'ai fini par comprendre qu'il y avait un problème potentiel avec le solver ET le modèle. 
J'ai ajouté un warning, comme solution un peu bancale.

**Comment by pnavaro** [comment]
J'étais en train de regarder et je ne comprends pas pourquoi tu n'utilises pas la fonction
solve! pour un probleme seul dans ta version pour résoudre plusieurs problemes.
