### ISSUE TITLE
Implement a recipe for the problem solution

### ISSUE THREAD

**Issue by pnavaro** [WaterWavesModels/WaterWaves1D.jl#18]

**Comment by pnavaro** [comment]
Bonjour Vincent

J'ai réussi à faire une fonction plot pour un problème, cependant cela ne peut pas fonctionner pour une série de problèmes. On peut faire

```julia
plot(WW_problem)
plot!(WW2_problem)
```

**Comment by vybduchene** [comment]
Super. J'imagine que l'on peut contourner le problème avec
function plots(problems)
    for pb in problems
          plot!(pb)
    end
end

Est-ce que les options de plot_solution (le temps, l'interpolation, etc.) sont encore fonctionnelles ?

**Comment by pnavaro** [comment]
> function plots(problems)
> for pb in problems
> plot!(pb)
> end
> end
Si on veut que supprimer `Plots` des dépendances, il ne faut plus que la fonction `plot` apparaisse dans le package.

> Est-ce que les options de plot_solution (le temps, l'interpolation, etc.) sont encore fonctionnelles ?

J'y travaille, ca ne devrait pas être trop dur. Je suis plus inquiet pour l'animation. Pour la différence je pensais proposer faire un truc du genre

```julia
plot(WW_problem - WW2_problem)
```
