### ISSUE TITLE
types sur recipes.jl

### ISSUE THREAD

**Issue by vybduchene** [WaterWavesModels/WaterWaves1D.jl#21]
La dernière update sur recipes.jl n'est vraiment pas très satisfaisante.
Le problème est le suivant. 
Si l'entrée est de type Vector{Problem}, alors plot effectue des graphiques sur tous les problèmes.
Si l'entrée est de type Vector{Tuple{Problem,Problem]}, alors plot effectue des _différences_ sur tous les problèmes.
Mais j'aimerais que l'utilisateur puisse donner une entrée de type Vector{Any}, qui est ce que l'on obtient si l'on fait
problems = []
puis
push!(problems, pb)
ou
push!(problems, (pb1,pb2))
Comment faire alors pour que plot sache quelle version utiliser ?
(mis à part ce que j'ai fait : rassembler les deux fonctions en une, et faire un test sur le premier élément de l'entrée)

**Comment by pnavaro** [comment]
si on fait
problems = Problem[]
puis
push!(problems, pb)

Ca marche ?

**Comment by pnavaro** [comment]
Avec Vector{Any} ca ne va pas être possible car il va y avoir un conflit avec la fonction plot générique

**Comment by vybduchene** [comment]
> si on fait problems = Problem[] puis push!(problems, pb)
> 
> Ca marche ?

Oui ça marche, mais il faut que l'utilisateur ait la présence d'esprit de le faire...

**Comment by vybduchene** [comment]
> Avec Vector{Any} ca ne va pas être possible car il va y avoir un conflit avec la fonction plot générique

Dans ce cas, visiblement, on remplace la fonction plot générique. C'est sans doute un peu problématique.

**Comment by vybduchene** [comment]
Je me range vers la solution qui parait la plus raisonnable : typer les entrées.
